# Generated by Django 4.1.7 on 2023-06-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tastTitle',
            new_name='taskTitle',
        ),
    ]
